#!/bin/bash

[[ ! -d /media/BC_1t/ ]] && { echo "BC_1t not mounted!" >&2; exit 1; }

rm *.THM

shopt -s extglob
rsync -ritP --remove-source-files --ignore-existing *.@(AVI|MOV) /media/BC_1t/dump_$(date '+%Y-%m-%d')/

ls # to show any missed files
