#!/bin/bash

if [[ $(findmnt -rno TARGET|grep -E '/media/|/mauto/') != "" ]]
then
  while read dev; do
  sudo umount "$dev" && echo -e '\E[32m'"\033[1m$dev\033[0m succesfully umounted!"
  done < <(findmnt -rno TARGET|grep -E '/media/|/mauto/')
else
  echo -e '\E[32m'"\033[1mNothing to be unmounted!\033[0m"
fi

conkyreload
