#!/bin/bash

while read -r line; do

	src="${line%:*}"
	dest="${line#*:}"

	echo "Moving from $src to $dest"

	mv "$src" "$dest"
	#sed -i -e "s/${src##*/}/${dest##*/}/g ${src%/*}/.picasa.ini"
	# if [[ -e "${src%/*}/.picasa.ini" ]]; then
	# 	replace "${src##*/}" "${dest##*/}" -- "${src%/*}/.picasa.ini"
	# fi
	# sed -i -e "s/${src##*/}/${dest##*/}/g" "$2"
	jhead -ft -q "$dest"

done <"$1"
