#!/bin/bash

while read -r -d $'\0' f; do

	echo '  <file created="'"$(date -d "@"$(stat -c %Z "$f")"" '+%d %b %Y %H:%M:%S %z')"'" modified="'"$(date -d "@"$(stat -c %Y "$f")"" '+%d %b %Y %H:%M:%S %z')"'">'
	echo "   <path>\\[P]\\$(echo "$f"|tr '/' '\\')</path>"
	echo '  </file>'

done < <(find * -type f -iname '*.ini' -print0)
