#!/bin/bash

ext=/dev/disk/by-label/BC_320G

if [[ -e $ext ]]; then
	if ! grep "$(readlink -fn $ext)" /proc/mounts >/dev/null; then
		unmounted="1"
		udisks --mount $ext >/dev/null
	fi
	rsnapshot "$1"
	if [[ $unmounted = "1" ]]; then
		udisks --unmount $ext
	fi
else
	echo "BC_320G not available!" >&2
	exit 1
fi
