#!/bin/bash

. "$(dirname $0)/pwd/syncemail"
. "$(dirname $0)/inc/auto_mnt"

auto_mnt BC_2T_ext

tb1="$(~/bin/synccheck|dos2unix|head -n-2|tail -n +2)"
[[ -n "$tb1" ]] && email+="New files on 1tb:"$'\n'"$tb1"$'\n\n'
pic2="$(unison -batch -terse pic2 2>/dev/null|dos2unix)"
[[ -n "$pic2" ]] && email+="Synchronized files in Picasa2 folders:"$'\n'"$pic2"$'\n\n'

auto_mnt BC_1T_ext

unison -batch -silent -path picasa 2tb
tb2="$(~/bin/synccheck 2tb|dos2unix|head -n-2|tail -n +2)"
[[ -n "$tb2" ]] && email+="New files on 2tb:"$'\n'"$tb2"$'\n\n'

auto_unmnt

if [[ -n "$email" ]]; then
	echo "$email"|mail -s "New files to sync" "$address"
fi
