#!/bin/bash

. "$(dirname $0)/pwd/syncemail"
. "$(dirname $0)/inc/auto_mnt"

auto_mnt BC_2T_ext

tb1="$(~/bin/synccheck|dos2unix|head -n-2|tail -n +2)"
[[ -n "$tb1" ]] && email+="New files on 1tb:"$'\n'"$tb1"$'\n\n'
pic2="$(~/bin/synccheck pic2|dos2unix|head -n-2|tail -n +2)"
[[ -n "$pic2" ]] && email+="New files in Picasa2 folders:"$'\n'"$pic2"$'\n\n'

auto_unmnt

auto_mnt BC_1T_ext BC_2T_ext

tb2="$(~/bin/synccheck 2tbslow|dos2unix|head -n-2|tail -n +2)"

auto_unmnt

if [[ -n "$email" ]]; then
	echo "$email"|mail -s "New files to sync" "$address"
fi
