#!/bin/bash

if [[ $1 = "" ]]; then
    WINEPREFIX="/home/bencahill/.wine_office/" wine "C:\Program Files\Microsoft Office\Office\WINWORD.EXE"
else
    WINEPREFIX="/home/bencahill/.wine_office/" wine start /ProgIDOpen Word.Document.8 "$1"
fi
