#!/bin/bash

if [ "$(xrandr | grep "VGA-1 connected")" ]
then 

# killall xmobar
killall -q dzen2
killall -q conky
killall -q tail
xrandr --output VGA-1 --mode 1280x1024 --rate 75.0 --left-of LVDS-1
xdotool key super+e
xdotool key super+1
bashrun --exit
imlibsetroot march-12-both.jpg &
# [[ -e /home/bencahill/.vol1 ]] && rm /home/bencahill/.vol1
# mkfifo /home/bencahill/.vol1
# [[ -e /home/bencahill/.vol ]] && rm /home/bencahill/.vol
# mkfifo /home/bencahill/.vol
# volupd &
# rm /home/bencahill/.xmb && mkfifo /home/bencahill/.xmb
tail -f /home/bencahill/.xmb | tee >(dzen2 -ta l -w 640 -fn "Terminus-6" -h 16 -bg gray20 -fg gray80 -xs 1) | dzen2 -ta l -w 640 -fn "Terminus-6" -h 16 -bg gray20 -fg gray80 -xs 2 &
conky | dzen2 -ta r -x 640 -w 640 -fn "Terminus-6" -h 16 -bg gray20 -fg gray80 -xs 1 &
conky | dzen2 -ta r -x 640 -w 640 -fn "Terminus-6" -h 16 -bg gray20 -fg gray80 -xs 2 &
# stalonetray -i 16 --geometry 1x1-0+0 -bg gray20 --sticky --skip-taskbar &
fi
